import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

import Navbar from "./_components/Navbar";
import { Toaster } from "./_components/ui/toaster";

const poppins = Poppins({
    subsets: ["latin"],
    weight: "400"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    return (
        <html lang="pt-br">
            <body className={poppins.className}>
                <main className="h-screen flex flex-col justify-center items-center">
                    <Navbar />
                    {children}
                </main>
                <Toaster />
            </body>
        </html>
    );
}
