import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Provider from "./_components/Provider";

import Navbar from "./_components/Navbar";
import { Toaster } from "./_components/ui/toaster";

const poppins = Poppins({
    subsets: ["latin"],
    weight: "400"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    return (
        <html lang="pt-br">
            <body className={poppins.className}>
                <Provider>
                    <main className="h-screen flex flex-col justify-center items-center">
                        <Navbar />
                        {children}
                    </main>
                    <Toaster />
                </Provider>
            </body>
        </html>
    );
}
